// Bakes levels/levels.js: 3 hand-made FTUE levels + generated levels 4..N (js/gen.js, the same code the game uses
// for endless levels after N). Every level is re-checked with the game's solver before it is written.
//
//   node tools/genlevels.mjs          100 levels
//   node tools/genlevels.mjs 120      another count
//   node tools/genlevels.mjs --dry    print the table only
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const COUNT = Number(process.argv.find((a) => /^\d+$/.test(a)) || 100);
const dry = process.argv.includes('--dry');

// the game's own modules in a sandbox: util (helpers), board (model + solver), gen (generator)
export function loadGame() {
  const ctx = { console, Math, performance: { now: () => 0 } }; ctx.window = ctx; vm.createContext(ctx);
  for (const f of ['js/util.js', 'js/board.js', 'js/gen.js']) vm.runInContext(fs.readFileSync(path.join(ROOT, f), 'utf8'), ctx, { filename: f });
  return ctx.AP;
}

// FTUE: one arrow; order (one blocks another); two short chains
const HAND = [
  { diff: 'easy', w: 3, h: 5, a: ['1,4:UUU'] },
  { diff: 'easy', w: 4, h: 5, a: ['0,2:RR', '3,4:UU'] },
  { diff: 'easy', w: 4, h: 4, a: ['0,0:DD', '0,3:RRR', '1,0:RR', '2,2:RU'] },
];

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const AP = loadGame();
  const levels = [...HAND];
  const t0 = Date.now();
  for (let n = HAND.length + 1; n <= COUNT; n++) {
    const lv = AP.gen.level(n);
    if (!lv) { console.error('FAIL  no level for', n); process.exit(1); }
    levels.push(lv);
  }
  let bad = 0; const rows = [];
  levels.forEach((lv, i) => {
    const errs = AP.board.validate(lv), order = AP.board.solve(lv), st = AP.gen.stats(lv);
    if (errs.length || !order) { bad++; console.error(`FAIL  L${i + 1}: ${errs.join(', ') || 'stuck'}`); }
    rows.push(`L${String(i + 1).padStart(3)}  ${lv.diff.padEnd(9)} ${String(lv.w + 'x' + lv.h).padEnd(6)} ${(lv.shape || 'rect').padEnd(9)} arrows ${String(st.arrows).padStart(3)}  depth ${String(st.layers).padStart(2)}  free@start ${String(st.free0).padStart(2)}  avg len ${st.len}`);
  });
  console.log(rows.join('\n'));
  console.log(`\n${levels.length} levels in ${Date.now() - t0} ms${bad ? `, ${bad} BAD` : ', all valid and solvable'}`);
  if (bad) process.exit(1);
  if (!dry) {
    const body = levels.map((lv) => '  ' + JSON.stringify(lv)).join(',\n');
    const out = `// ---------- Level data (GENERATED by tools/genlevels.mjs — do not edit by hand) ----------
// Format: { diff, w, h, shape?, a: ['x,y:MOVES', ...] }. An arrow starts at its tail cell (x, y) and walks MOVES
// (U D L R); the last move is the head direction. Levels after the last one come from AP.gen.level(n) at runtime.
AP.LEVELS = [
${body},
];
`;
    fs.writeFileSync(path.join(ROOT, 'levels', 'levels.js'), out);
    console.log('written levels/levels.js', (out.length / 1024).toFixed(1), 'KB');
  }
}
